In [1]:
import pandas as pd
import matplotlib.pyplot as pyplot
import seaborn as sns
import numpy as np

In [4]:
data = pd.read_csv("IceCreamDataSet.csv")

In [9]:
data = data.drop(["Unnamed: 0"], axis = 1)

,Customer,Date,Flavor,Revenue,Profit,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Drew Roulette,3/1/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
1,Don Frazon,3/2/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
2,Erin Davidson,3/2/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
3,Ted Price,3/2/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
4,Lila Stevens,3/3/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
5,Sierra Noonan,3/3/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
6,Ian Richardson,3/3/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
7,Drew Roulette,3/4/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
8,Sean Lansfrow,3/4/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
9,Malcolm Benjamin,3/4/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
10,Erin Davidson,3/6/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
11,Ted Price,3/6/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
12,Dennis Perelman,3/7/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
13,Lila Stevens,3/7/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
14,Silvio Carrera,3/7/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
15,Ted Price,3/8/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
16,Sierra Noonan,3/8/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
17,Sean Lansfrow,3/8/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
18,Tony DiCenzo,3/9/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
19,Malcolm Benjamin,3/9/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
20,Ian Richardson,3/10/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
21,Drew Roulette,3/10/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
22,Sierra Noonan,3/10/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
23,Don Frazon,3/10/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
24,Sean Lansfrow,3/11/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
25,Tony DiCenzo,3/11/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
26,Erin Davidson,3/11/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
27,Silvio Carrera,3/11/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
28,Dennis Perelman,3/11/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
29,Lila Stevens,3/11/18,Cookie Dough,$5.00,$3.75,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
56,Malcolm Benjamin,3/23/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
57,Silvio Carrera,3/24/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
58,Erin Davidson,3/24/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
59,Sean Lansfrow,3/24/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
60,Ian Richardson,3/24/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
61,Tony DiCenzo,3/25/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
62,Sierra Noonan,3/25/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
63,Ted Price,3/25/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
64,Ian Richardson,3/27/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
65,Erin Davidson,3/28/18,Vanilla,$2.00,$1.00,NaN,NaN,NaN,NaN
66,Silvio Carrera,3/28/18,Vanilla,$2.00,$1.00,NaN,NaN,NaN,NaN
67,Dennis Perelman,3/28/18,Chocolate,$2.00,$1.00,NaN,NaN,NaN,NaN
68,Don Frazon,3/28/18,Vanilla,$2.00,$1.00,NaN,NaN,NaN,NaN
69,Ted Price,3/28/18,Chocolate,$2.00,$1.00,NaN,NaN,NaN,NaN
70,Malcolm Benjamin,3/28/18,Chocolate Chip,$2.50,$1.25,NaN,NaN,NaN,NaN
71,Sean Lansfrow,3/28/18,Vanilla,$2.00,$1.00,NaN,NaN,NaN,NaN
72,Erin Davidson,3/28/18,Chocolate Chip,$2.50,$1.25,NaN,NaN,NaN,NaN
73,Tony DiCenzo,3/28/18,Chocolate Chip,$2.50,$1.25,NaN,NaN,NaN,NaN
74,Drew Roulette,3/28/18,Vanilla,$2.00,$1.00,NaN,NaN,NaN,NaN
75,Sierra Noonan,3/28/18,Chocolate,$2.00,$1.00,NaN,NaN,NaN,NaN
76,Ian Richardson,3/28/18,Vanilla,$2.00,$1.00,NaN,NaN,NaN,NaN
77,Silvio Carrera,3/28/18,Vanilla,$2.00,$1.00,NaN,NaN,NaN,NaN
78,Don Frazon,3/28/18,Chocolate Chip,$2.50,$1.25,NaN,NaN,NaN,NaN
79,Ian Richardson,3/29/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
80,Malcolm Benjamin,3/30/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN
81,Drew Roulette,3/30/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
82,Silvio Carrera,3/31/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
83,Sean Lansfrow,3/31/18,Vanilla,$4.00,$3.00,NaN,NaN,NaN,NaN
84,Ted Price,3/31/18,Chocolate,$4.00,$3.00,NaN,NaN,NaN,NaN
85,Don Frazon,3/31/18,Chocolate Chip,$5.00,$3.75,NaN,NaN,NaN,NaN

In [17]:
date_to_profits = {}
for index, row in data.iterrows():
    if row["Date"] not in date_to_profits:
        date_to_profits[row["Date"]] = float(row["Profit"][1:])
    else:
        date_to_profits[row["Date"]] = date_to_profits[row["Date"]] + float(row["Profit"][1:])

In [18]:
date_to_profits

{'3/1/18': 3.0,
 '3/10/18': 13.5,
 '3/11/18': 20.25,
 '3/13/18': 6.75,
 '3/14/18': 3.0,
 '3/15/18': 10.5,
 '3/16/18': 14.25,
 '3/17/18': 18.0,
 '3/18/18': 17.25,
 '3/2/18': 9.0,
 '3/20/18': 6.75,
 '3/21/18': 3.0,
 '3/22/18': 3.0,
 '3/23/18': 10.5,
 '3/24/18': 12.75,
 '3/25/18': 9.75,
 '3/27/18': 3.0,
 '3/28/18': 15.0,
 '3/29/18': 3.0,
 '3/3/18': 10.5,
 '3/30/18': 6.75,
 '3/31/18': 12.75,
 '3/4/18': 10.5,
 '3/6/18': 6.75,
 '3/7/18': 11.25,
 '3/8/18': 9.0,
 '3/9/18': 6.75}

In [22]:
sum = 0
for date in date_to_profits:
    sum += date_profits[date]
sum = sum

3/28/18
3/8/18
3/20/18
3/25/18
3/13/18
3/16/18
3/9/18
3/18/18
3/31/18
3/27/18
3/6/18
3/1/18
3/23/18
3/24/18
3/10/18
3/11/18
3/14/18
3/17/18
3/15/18
3/3/18
3/4/18
3/21/18
3/22/18
3/30/18
3/29/18
3/2/18
3/7/18

In [29]:
flavor_to_profits = {}
flavor_to_count = {}
for index, row in data.iterrows():
    if row["Flavor"] not in flavor_to_count:
        flavor_to_count[row["Flavor"]] = 1
    else:
        flavor_to_count[row["Flavor"]] = flavor_to_count[row["Flavor"]] + 1
    if row["Flavor"] not in flavor_to_profits:
        flavor_to_profits[row["Flavor"]] = float(row["Profit"][1:])
        
    else:
        flavor_to_profits[row["Flavor"]] = flavor_to_profits[row["Flavor"]] + float(row["Profit"][1:])

In [30]:
flavor_to_profits

{'Chocolate': 60.0,
 'Chocolate Chip': 53.75,
 'Cookie Dough': 48.75,
 'Mint Chip': 30.0,
 'Vanilla': 64.0}

In [31]:
flavor_to_count

{'Chocolate': 22,
 'Chocolate Chip': 17,
 'Cookie Dough': 13,
 'Mint Chip': 8,
 'Vanilla': 26}

In [33]:
average_flavor_to_profits = {}
for flavor in flavor_to_profits:
    average_flavor_to_profits[flavor] = flavor_to_profits[flavor] / flavor_to_count[flavor]

In [34]:
average_flavor_to_profits

{'Chocolate': 2.727272727272727,
 'Chocolate Chip': 3.161764705882353,
 'Cookie Dough': 3.75,
 'Mint Chip': 3.75,
 'Vanilla': 2.4615384615384617}

In [44]:
day_to_profits = {}
day_to_count = {}
for index, row in data.iterrows():
    if (index % 7) not in day_to_count:
        day_to_count[(index % 7)] = 1
    else:
        day_to_count[(index % 7)] = day_to_count[index % 7] + 1
    if (index % 7) not in flavor_to_count:
        day_to_profits[index % 7] = float(date_to_profits[row["Date"]])
    else:
        day_to_profits[index % 7] = day_to_profits[index % 7] + float(date_to_profits[row["Date"]])

In [45]:
day_to_profits

{0: 12.75, 1: 12.75, 2: 3.0, 3: 6.75, 4: 6.75, 5: 12.75, 6: 12.75}

In [47]:
day_to_count = {0: 5, 1: 5, 2: 5, 3: 4, 4: 4, 5: 4, 6: 4}

In [48]:
day_to_average = {}
for day in day_to_count:
    day_to_average[day] = day_to_profits[day] / day_to_count[day]

In [49]:
day_to_average

{0: 2.55, 1: 2.55, 2: 0.6, 3: 1.6875, 4: 1.6875, 5: 3.1875, 6: 3.1875}

In [51]:
date_to_profits = {}
for index, row in data.iterrows():
    if row["Customer"] not in date_to_profits:
        date_to_profits[row["Customer"]] = 1
    else:
        date_to_profits[row["Customer"]] = date_to_profits[row["Customer"]] + 1

In [52]:
date_to_profits

{'Dennis Perelman': 4,
 'Don Frazon': 8,
 'Drew Roulette': 7,
 'Erin Davidson': 6,
 'Ian Richardson': 7,
 'Lila Stevens': 5,
 'Malcolm Benjamin': 7,
 'Sean Lansfrow': 8,
 'Sierra Noonan': 10,
 'Silvio Carrera': 8,
 'Ted Price': 9,
 'Tony DiCenzo': 7}